# Generated by Django 6.0.2 on 2026-04-02 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id_quiz', models.AutoField(primary_key=True, serialize=False)),
                ('max_time', models.TimeField()),
                ('changeability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('time_begin', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField()),
                ('max_count_people', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id_reaction', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Cool', 'Cool'), ('Bad', 'Bad')], max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id_presentation', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to=settings.AUTH_USER_MODEL)),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations_in_session', to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id_member', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id_slide', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='slides/')),
                ('status', models.BooleanField(default=False)),
                ('id_presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='core.presentation')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id_widget', models.AutoField(primary_key=True, serialize=False)),
                ('id_slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='core.slide')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id_vote', models.AutoField(primary_key=True, serialize=False)),
                ('id_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.member')),
                ('id_presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_in_presentation', to='core.presentation')),
                ('id_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_in_quiz', to='core.quiz')),
                ('id_widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_in_widget', to='core.widget')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='id_widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='core.widget'),
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id_answer_option', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('text', models.CharField(max_length=50)),
                ('id_widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='core.widget')),
            ],
        ),
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('id_word_cloud', models.AutoField(primary_key=True, serialize=False)),
                ('word_limit', models.IntegerField()),
                ('question', models.CharField(max_length=50)),
                ('id_widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_clouds', to='core.widget')),
            ],
        ),
    ]
