# Generated by Django 6.0.2 on 2026-05-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_presentation_id_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='slide_type',
            field=models.CharField(default='CONTENT', max_length=20),
        ),
    ]
