# Generated by Django 6.0.2 on 2026-05-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_slide_slide_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
