# Generated by Django 6.0.2 on 2026-06-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_session_current_slide_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='current_slide_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='allow_change_answer',
            field=models.BooleanField(default=False, help_text='Разрешить изменить ответ до окончания таймера'),
        ),
        migrations.AddField(
            model_name='slide',
            name='timer',
            field=models.IntegerField(blank=True, default=None, help_text='Время на ответ в секундах', null=True),
        ),
    ]
